from logging import exception

from backend.celery import app
from .services.functions import check_for_new_exploit


@app.task()
def check_for_new_exploit_task():
    try:
        check_for_new_exploit()
    except Exception as exception_error:
        exception(
            f'~~~~~~~~~~~~~~~\n{exception_error}\n~~~~~~~~~~~~~~~'
        )
